apiVersion: auth.halo.run/v1alpha1
kind: AuthProvider
metadata:
  name: github
  labels:
    auth.halo.run/auth-binding: "true"
spec:
  displayName: GitHub
  description: GitHub Inc. is an Internet hosting service for software development and version control using Git.
  logo: /plugins/plugin-oauth2/assets/static/github.svg
  website: https://github.com
  helpPage: https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app
  authenticationUrl: /oauth2/authorization/github
  bindingUrl: /oauth2/authorization/github
  unbindUrl: /apis/uc.api.auth.halo.run/v1alpha1/user-connections/github/disconnect
  authType: oauth2
  settingRef:
    name: generic-oauth2-setting
    group: genericOauth
  configMapRef:
    name: oauth2-github-config
---
apiVersion: auth.halo.run/v1alpha1
kind: AuthProvider
metadata:
  name: gitee
  labels:
    auth.halo.run/auth-binding: "true"
spec:
  displayName: Gitee
  description: Gitee is an online forge that allows software version control using Git and is intended primarily for the hosting of open source software.
  logo: /plugins/plugin-oauth2/assets/static/gitee.svg
  website: https://gitee.com
  authenticationUrl: /oauth2/authorization/gitee
  bindingUrl: /oauth2/authorization/gitee
  unbindUrl: /apis/uc.api.auth.halo.run/v1alpha1/user-connections/gitee/disconnect
  authType: oauth2
  settingRef:
    name: generic-oauth2-setting
    group: genericOauth
  configMapRef:
    name: oauth2-gitee-config
---
apiVersion: auth.halo.run/v1alpha1
kind: AuthProvider
metadata:
  name: gitlab
  labels:
    auth.halo.run/auth-binding: "true"
spec:
  displayName: GitLab
  description: GitLab Inc. is an open-core company that operates GitLab, a DevOps software package which can develop, secure, and operate software.
  logo: /plugins/plugin-oauth2/assets/static/gitlab.svg
  website: https://gitlab.com
  authenticationUrl: /oauth2/authorization/gitlab
  bindingUrl: /oauth2/authorization/gitlab
  unbindUrl: /apis/uc.api.auth.halo.run/v1alpha1/user-connections/gitlab/disconnect
  authType: oauth2
  settingRef:
    name: generic-oauth2-setting
    group: genericOauth
  configMapRef:
    name: oauth2-gitlab-config
---
apiVersion: auth.halo.run/v1alpha1
kind: AuthProvider
metadata:
  name: wechat
  labels:
    auth.halo.run/auth-binding: "true"
spec:
  displayName: WeChat
  description: WeChat is a multi-purpose messaging, social media, and mobile payment app.
  logo: /plugins/plugin-oauth2/assets/static/wechat.svg
  website: https://open.weixin.qq.com
  authenticationUrl: /oauth2/authorization/wechat
  bindingUrl: /oauth2/authorization/wechat
  unbindUrl: /apis/uc.api.auth.halo.run/v1alpha1/user-connections/wechat/disconnect
  authType: oauth2
  settingRef:
    name: generic-oauth2-setting
    group: genericOauth
  configMapRef:
    name: oauth2-wechat-config
---
apiVersion: auth.halo.run/v1alpha1
kind: AuthProvider
metadata:
  name: qq
  labels:
    auth.halo.run/auth-binding: "true"
spec:
  displayName: QQ
  description: QQ is a popular instant messaging software in China.
  logo: /plugins/plugin-oauth2/assets/static/qq.svg
  website: https://graph.qq.com
  authenticationUrl: /oauth2/authorization/qq
  bindingUrl: /oauth2/authorization/qq
  unbindUrl: /apis/uc.api.auth.halo.run/v1alpha1/user-connections/qq/disconnect
  authType: oauth2
  settingRef:
    name: generic-oauth2-setting
    group: genericOauth
  configMapRef:
    name: oauth2-qq-config
---
apiVersion: auth.halo.run/v1alpha1
kind: AuthProvider
metadata:
  name: baidu
  labels:
    auth.halo.run/auth-binding: "true"
spec:
  displayName: Baidu
  description: Baidu is a leading Chinese search engine and AI company.
  logo: /plugins/plugin-oauth2/assets/static/baidu.svg
  website: https://openapi.baidu.com
  authenticationUrl: /oauth2/authorization/baidu
  bindingUrl: /oauth2/authorization/baidu
  unbindUrl: /apis/uc.api.auth.halo.run/v1alpha1/user-connections/baidu/disconnect
  authType: oauth2
  settingRef:
    name: generic-oauth2-setting
    group: genericOauth
  configMapRef:
    name: oauth2-baidu-config
---
apiVersion: auth.halo.run/v1alpha1
kind: AuthProvider
metadata:
  name: aliyun
  labels:
    auth.halo.run/auth-binding: "true"
spec:
  displayName: AliCloud
  description: Alibaba Cloud provides cloud computing services.
  logo: /plugins/plugin-oauth2/assets/static/aliyun.svg
  website: https://www.aliyun.com
  authenticationUrl: /oauth2/authorization/aliyun
  bindingUrl: /oauth2/authorization/aliyun
  unbindUrl: /apis/uc.api.auth.halo.run/v1alpha1/user-connections/aliyun/disconnect
  authType: oauth2
  settingRef:
    name: generic-oauth2-setting
    group: genericOauth
  configMapRef:
    name: oauth2-aliyun-config
