apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: github
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/github"
  scopes:
    - "read:user"
  authorizationUri: "https://github.com/login/oauth/authorize"
  tokenUri: "https://github.com/login/oauth/access_token"
  userInfoUri: "https://api.github.com/user"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "id"
  clientName: "GitHub"
---
apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: gitee
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/gitee"
  scopes:
    - "user_info"
  authorizationUri: "https://gitee.com/oauth/authorize"
  tokenUri: "https://gitee.com/oauth/token"
  userInfoUri: "https://gitee.com/api/v5/user"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "login"
  clientName: "Gitee"
---
apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: gitlab
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/gitlab"
  scopes:
    - "read_user"
  authorizationUri: "https://gitlab.com/oauth/authorize"
  tokenUri: "https://gitlab.com/oauth/token"
  userInfoUri: "https://gitlab.com/api/v4/user"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "username"
  clientName: "GitLab"
---
apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: wechat
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/wechat"
  scopes:
    - "snsapi_login"
  authorizationUri: "https://open.weixin.qq.com/connect/qrconnect"
  tokenUri: "https://api.weixin.qq.com/sns/oauth2/access_token"
  userInfoUri: "https://api.weixin.qq.com/sns/userinfo"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "openid"
  clientName: "WeChat"
---
apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: qq
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/qq"
  scopes:
    - "get_user_info"
  authorizationUri: "https://graph.qq.com/oauth2.0/authorize"
  tokenUri: "https://graph.qq.com/oauth2.0/token"
  userInfoUri: "https://graph.qq.com/user/get_user_info"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "openid"
  clientName: "QQ"
---
apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: baidu
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/baidu"
  scopes:
    - "basic"
  authorizationUri: "https://openapi.baidu.com/oauth/2.0/authorize"
  tokenUri: "https://openapi.baidu.com/oauth/2.0/token"
  userInfoUri: "https://openapi.baidu.com/rest/2.0/passport/users/getInfo"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "openid"
  clientName: "Baidu"
---
apiVersion: oauth.halo.run/v1alpha1
kind: Oauth2ClientRegistration
metadata:
  name: aliyun
spec:
  clientAuthenticationMethod: "client_secret_basic"
  authorizationGrantType: "authorization_code"
  redirectUri: "{baseUrl}/login/oauth2/code/aliyun"
  scopes:
    - "user:read"
  authorizationUri: "https://oauth.aliyun.com/v1.0/authorize"
  tokenUri: "https://oauth.aliyun.com/v1.0/token"
  userInfoUri: "https://oauth.aliyun.com/v1.0/userinfo"
  userInfoAuthenticationMethod: "header"
  userNameAttributeName: "user_id"
  clientName: "AliCloud"
